### ISSUE TITLE
Data generation

### ISSUE THREAD

**Issue by antonioFlavio** [flexudy-pipe/sentence-doctor#1]
Thank you a lot for sharing this model with us.

I would like to know  more about the synthetic data generation that you have done. Could you share which types os transformations on sentence did you perform?

**Comment by zolekode** [comment]
Hello @antonioFlavio sorry for responding this late. I don't receive notifications for some reason.

I will try to answer this question as detailed as possible:

1. First, i collect data (just a bunch of sentences. In my case, the tatoeba dataset).
Remember: The goal is to repair a sentence given an optional context (surrounding sentences). 

2. Since sentences are independent of one another, i don't have a context. So to generate a pseudo context, I compute the sentence vectors for each sentence and save them in a Ball Tree (something like a binary tree for efficient vector search).

3. For each sentence **Sx**, i look for the two closest sentences in the Ball tree. I then use these sentences as context. Randomly picking one sentence as the prefix (sentence "occurring" before the **Sx**) and the other as suffix (sentence occurring after **Sx**).

4. At this point, a row in my data looks like this: < some_sentence. **Sx**. some_other_sentence >. Let us assume this is an example: "_Hello good morning_. **How are you today ?** _The weather is beautiful._"

5. Our sentence of interest is **How are you today ?**. Time to generate some noise.

i. With a probability of _p_ (e.g 0.3), extend the sentence by _n_ words extracted from its prefix context. Example where _n=2_ we obtain **good morning. How are you today ?**

ii. Similarly extend the sentence by _n_ words extracted from the suffix with some probability _p_. E.g _n=1_ produces **good morning. How are you today ? The**

iii. Randomly cut x% of the characters in a sentence with some probability and append it to the context. Example: The sentence **"The boys."** has 10 characters. So, cutting 20% from the start produces **e boys.** This transformation can be applied to the start or end of a sentence.

iv. Randomly delete or replace characters _n_ in a sentence. E.g **The boys.** can then be **Th boy** or **Thbo yss**. Characters used to replace are randomly picked from the sentence itself.

v. Delete context. The context might be removed completely, so the model has no chance to "peep" during correction.

Note that all these transformations can be carried out in any order and are applied successively. I set the max number of transformations to 2 and the minimum to 0. Thus, given some probability _p_, apply no transformation. In my case it was **p=0.15**. 

I will try to find time to release the script so you can take a look and possibly correct errors if any. This was super long but i jope it helps.

Cheers.

**Comment by antonioFlavio** [comment]
Thank you a lot @zolekode for the detailed description of the process. I liked that ideia to create a synthetic context with closest sentences. I appreciate if you could share the script too.

**Comment by zolekode** [comment]
@antonioFlavio Let me see what i can do 💯

**Comment by zolekode** [comment]
there you go @antonioFlavio https://github.com/flexudy-pipe/sentence-doctor/pull/3

it is now merged to master. You can play with the script

**Comment by antonioFlavio** [comment]
Thank you a lot @zolekode !!
